---

- name: NGINX | Installing NGINX
  sudo: yes
  apt:
    name: nginx
    state: latest
    update_cache: yes
 
- name: NGINX | Starting NGINX
  sudo: yes
  service:
    name: nginx
    state: started

# - name: Copy nginx configuration 
#   template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#   notify: restart nginx

- name: Setup static Directories
  sudo: yes
  file: >
    state=directory
    path="{{ item }}"
    mode=755
  with_items:
      - /var/www/html/

- name: Copy Flask Static files
  sudo: yes
  copy: 
    src : static/
    dest: "/var/www/html/static/"


- name: Copy nginx configuration 
  sudo: yes
  copy: 
    src : templates/default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx