---


- name: Install MySQL
  apt: 
    name: "{{ item }}"
    update_cache: yes 
    state: present
  sudo: yes
  with_items:
    - python-mysqldb
    - mysql-server

- name: Start the MySQL service
  sudo: yes
  service: 
    name: mysql 
    state: started
    enabled: true
- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: 
    name: "{{ db_user }}" 
    host: "{{ item }}" 
    password: "{{ db_password }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - 10.0.0.11
    - 10.0.0.12
    - 10.0.0.13
    - ::1
    - localhost 



- name: Create a new database with name 'webapp'
  mysql_db:
    name: webapp
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
  register: db_created

- name: Copy SQL config file
  sudo: yes
  copy: >
    src=my.cnf
    dest="/etc/mysql/my.cnf"
    mode=755
  notify: restart mysql



- name: Copy SQL Dump
  sudo: yes
  copy: >
    src=pets.sql
    dest="/tmp/pets.sql"
    mode=755

- name: Import database
  sudo: yes
  mysql_db:
    state: import
    name: webapp
    target: "/tmp/pets.sql"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
  when: db_created.changed

